baseURL = "https://erpressa.github.io/blog/"
languageCode = "en-us"
theme = "glim-midnight"

publishDir = "."
[params]
    title = "Benvenuto"
    phrases = ["Nel", "Blog", "Di", "Cristiano", "Giannini"]
    links = [
    {name = "Github", url = "https://github.com/erpressa"},
    {name = "In", url = "/wiki"},
    {name = "Allestimento", url = "https://github.com/erpressa"}
    ]
    background = "bg.mp4"

